package `2023_03_02`

fun main() {
    val monitor = Monitor("Dell", "2419P", 12999.00)
    println("monitor: $monitor")

    println("${monitor.name}")
    monitor.name = "24 inch monitor"
}

/**
 * Getters and setters are implicit. They are autogenerated by the default
 * object.property accesses the getter implicitly, properties are never accessed directly
 * Encapsulation and abstraction: Hide working to the outside world
 */
class Monitor(
    name: String,
    val model: String,
    val price: Double
) {
    //This is implicit code generated by Kotlin on var properties
    //'field' and 'value' are keywords that can only be accessed within the getters and setters
    var name = name
        get() = "Name: $field"
        set(value) {
            println("Assigning '$value' to name field")
            //this.name = name would have been equivalent to calling the setter again
            field = value
        }

    override fun toString() = "Monitor(name='$name', model='$model', price=$price)"
}